[build]
  args_bin = ["serve", "examples/capacitor.schemgo"]
  exclude_dir = ["docs", "examples", "build"]

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
