[tools]
go = "latest"
mdbook = "latest"
"ubi:badboy/mdbook-mermaid" = "latest"
"ubi:tommilligan/mdbook-admonish" = "latest"
"ubi:jonahgoldwastaken/mdbook-external-links" = "latest"
"ubi:hypergonial/mdbook-autosummary" = "latest"


[tasks.simple]
alias = 's'
run = "go run . -i examples/simple.schemgo -o simple.svg"
sources = [
	'**/*.go',
	'examples/simple.schemgo'
]
outputs = 'simple.svg'
