[tools]
air = "latest"

[tasks.build]
alias = 'b'
run = 'go run . build {{"examples/"~arg(i=1,name="input_file")}} -o build/out.svg'
sources = [
	'**/*.go',
	'examples/'
]
outputs = { auto = true }

[tasks.clean]
alias = 'c'
run = 'rm -rf build/ tmp/'
