[tools]
"go" = "latest"
"go:golang.org/x/tools/cmd/godoc" = "latest"

[tasks.simple]
alias = 's'
run = "go run . -i examples/simple.schemgo -o simple.svg"
sources = [
	'**/*.go',
	'examples/simple.schemgo'
]
outputs = 'simple.svg'
