[tools]
uv = "latest"
air = "latest"
go = "latest"
"pipx:mkdocs" = { version = "latest", uvx_args = "--with mkdocs-material" }

[tasks.build]
alias = 'b'
run = 'go run . build -o build/out.svg'

[tasks.serve]
alias = 's'
run = 'go run . serve'

[tasks.clean]
alias = 'c'
run = 'rm -rf schemgo ./bench.txt ./*.svg tmp/ $GOBIN/schemgo'

[tasks.bench]
shell = 'bash -c'
run = "go tool benchstat <(go test -bench=. -count=8 -run=^a ./...)"
