[tools]
air = "latest"

[tasks.build]
alias = 'b'
run = 'go run . build -o build/out.svg'

[tasks.serve]
alias = 's'
run = 'go run . serve'

[tasks.clean]
alias = 'c'
run = 'rm -rf schemgo tmp/ $GOBIN/schemgo'
