[tools]
"go" = "latest"
"go:golang.org/x/tools/cmd/godoc" = "latest"

[vars]
input = 'examples/simple.schemgo'
out_dir = 'build/'

[tasks.simple]
alias = 's'
run = 'go run . -i {{ vars.input }} -o {{ [ vars.out_dir ] | concat(with=vars.input|basename) | join_path }}'
sources = [
	'**/*.go',
	'{{ vars.input }}'
]
outputs = '{{ [ vars.out_dir ] | concat(with=vars.input|basename) | join_path }}'


[tasks.clean]
alias = 'c'
run = 'rm -rf {{ vars.out_dir }}'
