[tools]
air = "latest"
go = "latest"
"go:golang.org/x/perf/cmd/benchstat" = "latest"

[tasks.build]
alias = 'b'
run = 'go run . build -o build/out.svg'

[tasks.serve]
alias = 's'
run = 'go run . serve'

[tasks.clean]
alias = 'c'
run = 'rm -rf schemgo ./bench.txt ./*.svg tmp/ $GOBIN/schemgo'

[tasks.bench]
run = """
benchstat <(go test -bench=. -count=8 -run=^a ./...)
"""
