[tools]
go = "latest"

[tasks.simple]
alias = 's'
run = "go run . build examples/simple.schemgo -o simple.svg"
sources = [
	'**/*.go',
	'examples/simple.schemgo'
]
outputs = 'simple.svg'

[tasks.comments]
alias = 'c'
run = "go run . build examples/comments.schemgo -o comments.svg"
sources = [
	'**/*.go',
	'examples/comments.schemgo'
]
outputs = 'comments.svg'
