session: schemgo

root: .

windows:
  - name: vim

  - name: example
    commands:
      - vim examples/simple.schemgo

  - name: watch
    commands:
      - mise watch simple
    after_start:
      - eog build/simple.svg
