# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: schemgo

repo_name: sermuns/schemgo
repo_url: https://github.com/sermuns/schemgo

site_dir: public

nav:
  - Home: index.md
  - Overview: overview.md
  - Installation: installation.md
  - Tutorial:
    - Getting started: getting-started.md
    - "mdBook preprocessor": mdbook.md
  - Reference:
    - Components: components.md
  - Examples: examples.md

extra_css:
  - style.css

theme:
  name: material
  favicon: media/logo.svg
  logo: media/logo.svg
  features: 
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  font:
    text: Inter
    code: JetBrains Mono

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
