name: Benchmark

concurrency:
  group: release
  cancel-in-progress: true

env:
  REPO_NAME: schemgo

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/benchmark.yml'
      - '**/*.go'
  workflow_dispatch:

jobs:
  bench:
    name: Benchmark code
    runs-on: ubuntu-24.04
    steps:

      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Tools
        uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: Benchmark
        run: mise bench
