name: Deploy documentation
on:
  push:
    branches:
      - main
    paths:
      - 
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: true

defaults:
  run:
    working-directory: docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to push a branch
      pages: write # to push to a github pages site
      id-token: write # to update the deployment status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        uses: jdx/mise-action@v2

      - name: Build mdBook
        run: |
          touch src/SUMMARY.md
          mdbook build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/build"

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
